### PR TITLE
Update deploy with balena

### PR DESCRIPTION
**Pull request by shawaj**
Change to new svg logo and add query string parameters

### CODE REVIEW

**Review by just4give — APPROVED** [review]

**Comment by just4give** [comment]
Thanks @shawaj for the PR

**Comment by shawaj** [comment]
No probs @just4give :-)

**Comment by shawaj** [comment]
@just4give by the way - I am looking forward to building this project for my mother in law inside a Naturebytes case! Think it will go down very well - she loves birdwatching in the garden and feeding them all!

**Comment by just4give** [comment]
Awesome! Please share some photos when it's done :)

**Comment by shawaj** [comment]
Will do!

**Pull request merged**
